### ISSUE TITLE
Verify Signature with only builtins packages

### ISSUE THREAD

**Issue by RobinFrcd** [keygen-sh/example-python-offline-validation-caching#1]
Hi @ezekg,
Thanks you for your awesome [documentation](https://keygen.sh/docs/api/#response-signatures)!

The signature verification with [Cryptography](https://pypi.org/project/cryptography/) is working fine, but I'd like to know if there's a way to do this verification with built-ins packages only like `hashlib`.

Thanks,

**Comment by ezekg** [comment]
Unfortunately, I don't think that's possible. As far as I know, Python's standard library does not support Ed25519 or RSA verification functions, so a package such as Cryptography will need to be used to cryptographically verify signatures.

**Comment by RobinFrcd** [comment]
Alright, that's what I thought. Thanks for the insight!
